### ISSUE TITLE
Add General/Bus pin definitions to variant.h

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/MicroMod_Processor_Board-SAMD51#1]
### Subject of the issue
To the best of my knowledge, the SAMD51 Processor board definition appears to be missing (at least) all General/Bus pin definitions in its `variant.h` file.

### Your workbench
* What development board or microcontroller are you using?
  * MicroMod SAMD51 Processor
* What version of hardware or breakout board are you using? 
  * MicroMod Data Logging Carrier Board (MMDLCB)
* How is everything being powered?
  * USB-C

### Steps to reproduce
* Connect the SAMD51 Processor to the Data Logging Carrier Board and attempt to compile the MMDLCB Peripheral_Power_Control example:
https://github.com/sparkfun/MicroMod_Data_Logging_Carrier/blob/master/Examples/Peripheral_Power_Control/Peripheral_Power_Control.ino

### Expected behavior
Code should compile as normal.

### Actual behavior
```
Peripheral_Power_Control:5:16: error: 'G0' was not declared in this scope
 int headerCS = G0;
                ^
Peripheral_Power_Control:6:30: error: 'G1' was not declared in this scope
 int peripheralPowerControl = G1;
                              ^
Peripheral_Power_Control:7:25: error: 'G2' was not declared in this scope
 int qwiicPowerControl = G2;
                         ^
exit status 1
```

While I've been able to determine the physical pin numbers on the SAMD51 of G0/G1/G2 power control pins, referencing them directly doesn't work. I believe this most likely has something to do with the SAMD51 being multiplexed.

![image](https://user-images.githubusercontent.com/22924092/98038858-cc7a0180-1deb-11eb-95b3-e8158ec4b1af.png)

**Comment by adamgarbo** [comment]
Ah, of course, I figure it out immediately after! I see now in the schematic how the pins are related: G0/D2, G1/D3, G2/D4
Using these pin definitions, I'm able to control the G1/G2 regulators on the MMDLCB directly. 

The question is, should all of the "G"s be included in the variant.h file, or should users simply use their digital pin equivalents? For example, the Artemis variant.h file has all of the General/Bus pins defined. I suppose consistency is key!

```
#define G0 16
#define G1 33
#define G2 34
#define G3 27
#define G4 28
#define G5 29
#define G6 14
#define G7 15
#define G8 3
#define G9 ADC_DIFF_NEG
#define G10 ADC_DIFF_POS
#define G11 11
```

Cheers,
Adam

**Comment by edspark** [comment]
Ah this is a great idea, something I had considered and not sure why I didn't do. Thanks for bringing it back to my attention - I'll roll it into a release soon.

**Comment by edspark** [comment]
Thanks for the issue, the `#defines` for the relevant pins on the SAMD51 Micromod have been added to our Arduino Boards repository. I did not add ADC related `#defines` as they are not physically routed in such a way on the SAMD51 Micromod. I've also added keywords to that repository so that they're highlighted when you use the general pin nomenclature: `G0`, `G1`, etc... You can find these changes in the [1.7.8 release](https://github.com/sparkfun/Arduino_Boards/commit/cf6146e5421a28d8b91430474607ebbde78a0eef).
