### ISSUE TITLE
Swapped SPI1 lines

### ISSUE THREAD

**Issue by shale-bridge** [sparkfun/MicroMod_Processor_Board-SAMD51#2]
### Swapped SPI1 lines
External W25Q128 flash CIPO/COPI lines are swapped, so flash is unusable with SPI.

### Equipment
* SAMD51 MicroMod v1.2
* ATP (All-The-Pins) v1.1 breakout
* Custom motherboard

### Workaround
Swapping the CIPO/COPI lines in software and manually (bit-banging) data to/from the flash chip.

**Comment by edspark** [comment]
Thanks for the issue, a fix is on the way. I'll update in a few weeks when the new version is ready. When that happens feel free to reach out to SparkFun's customer service to get a replacement.

**Comment by stonehippo** [comment]
Any update on this @edspark? Would love to get a board with working external flash.

**Comment by shale-bridge** [comment]
Looks like all SAMD51 chips are on backorder until well into next year (Estimates at Nov/Dec 2022 before any stock becomes available, possibly 2/15/2022 for the SAMD51J20A).

**Comment by shale-bridge** [comment]
@stonehippo If you already have a SAMD51 MicroMod, I made a library that works with the layout error through software bit-banging.

[SAMD51 Bit Bang Library](https://github.com/shale-bridge/samd51-micromod-bitbang)

**Comment by stonehippo** [comment]
Thanks, @shale-bridge, I saw that, and I’ll probably use it for Arduino until we can get updated boards.

I had ported CircuitPython to this board, but not having the external flash makes that sorta nasty. I was going to look into making a personal patch to try using your idea to enable bitbang serial for this board there, too.

**Comment by edspark** [comment]
Hello everyone, yes it took a bit longer for the boards to arrive but they're expected sometime this week. After they received it will take a week or two to get back on storefront.

**Comment by stonehippo** [comment]
@edspark I got a back in stock notification on the module (though the site is still showing it as backorder). Has the new version arrived? If so, what's the best way to exchange the previous version?

**Comment by edspark** [comment]
Hey @stonehippo, I do see we have the PCBs in stock and I'm currently inquiring as to when they will be moved through production to get them back onto the website. The best way is to exchange your old one is go through the process [listed here](https://www.sparkfun.com/returns).

**Comment by edspark** [comment]
I've finally merged in the latest branch with the fix. I've tested the lines using [SparkFun's SPI SerialFlash library](https://github.com/sparkfun/SparkFun_SPI_SerialFlash_Arduino_Library) and I can now finally close this issue.

**Comment by stonehippo** [comment]
@edspark could you share the test code you used? I want to jump on fixing the support in CircuitPython and that will help.

**Comment by edspark** [comment]
Example here in the SparkFun SPI SerialFlash Library: 
https://github.com/sparkfun/SparkFun_SPI_SerialFlash_Arduino_Library/blob/main/examples/SPI_Flash_Example/SPI_Flash_Example.ino

**Comment by stonehippo** [comment]
Thanks, I was hoping for the exact changes you made to that example (i.e. did you need to set the HOLD and WP pins high, and what pins did you use, etc). If you used it as-is, great!

**Comment by edspark** [comment]
No problem, below is the modified code. I had to change _chip select_ and added some variables for the _write protect_ and _hold_ pins. In addition, because the flash is used on `SPI1`, the `begin` function needed additional arguments. 
```c++
const byte PIN_FLASH_CS = CS1; // Change this to match the Chip Select pin on your board
const byte WP_PIN = 15;
const byte HOLD_PIN = 16; 

#include <SPI.h>

#include <SparkFun_SPI_SerialFlash.h> //Click here to get the library: http://librarymanager/All#SparkFun_SPI_SerialFlash
SFE_SPI_FLASH myFlash;

void setup()
{
  Serial.begin(115200);
  while(!Serial){delay(1000);}
  Serial.println(F("SparkFun SPI SerialFlash Example"));

  pinMode(WP_PIN, OUTPUT); digitalWrite(WP_PIN, HIGH); // Uncomment this line to use pin 2 to pull up (e.g.) the WP/IO2 pin
  pinMode(HOLD_PIN, OUTPUT); digitalWrite(HOLD_PIN, HIGH); // Uncomment this line to use pin 3 to pull up (e.g.) the HOLD/IO3 pin

  myFlash.enableDebugging(); // Uncomment this line to enable helpful debug messages on Serial

  // Begin the flash using the chosen CS pin. Default to: spiPortSpeed=2000000, spiPort=SPI and spiMode=SPI_MODE0
  if (myFlash.begin(PIN_FLASH_CS, 2000000, SPI1) == false)
  {
    Serial.println(F("SPI Flash not detected. Check wiring. Maybe you need to pull up WP/IO2 and HOLD/IO3? Freezing..."));
    while (1);
  }
```

**Comment by stonehippo** [comment]
Thanks!

**Comment by stonehippo** [comment]
Thanks for the support, @edspark! I was able finally able to get the flash working with Circuitpython.
